### ISSUE TITLE
ConfigParser support passing a file object to .write(), INI doesn't

### ISSUE THREAD

**Issue by Anaphory** [clld/clldutils#37]
With `argparse.FileType`, I can easily create file objects. Passing such an object to configparser.ConfigParser is fine, but inifile.INI tries to convert it into a Path and then open it.

Similarly, this means I cannot just pass `sys.stdout` to `.write`.

**Comment by xrotwang** [comment]
I can see this issue with `INI.write`, but `ConfigParser.__init__` isn't overwritten by `INI`, and `INI.from_file` does not cast to `Path`.

**Comment by Anaphory** [comment]
Hm, true and very obvious. Maybe I was confusing it with something beastling does before delegating the reading to `INI`, sorry.

**Comment by xrotwang** [comment]
Writing unicode strings to `sys.stdout` isn't straightforward to do across platforms and python versions. So having to pass a path to `INI.write` or alternatively using `INI.write_string` to retrieve the formatted content as string seem safer and sufficient to fulfill all use cases.
