### ISSUE TITLE
csvw: Only start of string is checked with regex

### ISSUE THREAD

**Issue by xrotwang** [clld/clldutils#56]
The regex passed as `datatype.format` is compiled

https://github.com/clld/clldutils/blob/2d524d246b96b9a96ade428df422af1c0d60d1b8/clldutils/csvw/datatypes.py#L54

and then run using the `match` method, which will allow strings which start with a matching pattern to validate.

**Comment by xrotwang** [comment]
The simplest solution seems to be to tack `$` onto the regex. This doesn't even seem to harm when there's already a `$` present.

**Comment by xflr6** [comment]
Also a group around the pattern (regex operator precedence is tricky):
```python
>>> import re
>>> re.match(r'spam|eggs$', 'spamham')
<_sre.SRE_Match object at 0x00000000046991D0>
>>> re.match(r'(?:spam|eggs)$', 'spamham')
```
[mrab-regex](https://pypi.python.org/pypi/regex) is a little nicer: it has `fullmatch()`
