### ISSUE TITLE
Allow proper inheritance for clldutils.inifle.INI

### ISSUE THREAD

**Issue by xrotwang** [clld/clldutils#61]
The constructor classmethod's must actually use the `cls` argument.

**Comment by xflr6** [comment]
I think we already fixed this in d6556797a238dd7ce4b5debf87c2eb1bee2d4a1b
However, there is still this line here that can be changed to using `super`:
https://github.com/clld/clldutils/blob/d6556797a238dd7ce4b5debf87c2eb1bee2d4a1b/clldutils/inifile.py#L32

**Comment by xrotwang** [comment]
Ah right. It's just not released yet. Sorry.
