### ISSUE TITLE
Remove the \ufeff character from any file that is read?

### ISSUE THREAD

**Issue by LinguList** [clld/clldutils#65]
This is the 10th time that I had these issues: reading in a file, searching for a header, I see an error, and only in the end I find out, why the header (in this case "ID") was not found: The first character was ```\ufeffID```.

This happened in the concepticon-api, which uses clldutils, and I wonder, given that this usually leads to a long debugging session, whether we should not remove this character immediately if it occurs as the header? Or are there other preferred ways how to deal with it?

**Comment by xflr6** [comment]
It's a [BOM](https://de.wikipedia.org/wiki/Byte_Order_Mark), which technically is not needed for `utf-8` but M$ (notepad?) had the idea to put it there anyway to indicate encoding.

Use `encoding='utf-8-sig'` when opening (that will just ignore it for you). See also https://docs.python.org/2/library/codecs.html#encodings-and-unicode

**Comment by xrotwang** [comment]
Yeah, that's probably an easy fix.

**Comment by LinguList** [comment]
Excellent! But this should ideally just be done in clldutils, right?

**Comment by xflr6** [comment]
If the default is `utf-8` there we could change it to `utf-8-sig` (but not for writing, right?), but I guess it is always better to be explicit about the encoding you use when opening a text file.

**Comment by LinguList** [comment]
The problem is: whenever a user provides a textfile from notepad, and I want to read it as conceptlist in concepticon, it throws an error for the moment. And since concepticon uses the clldutils-api, it needs to be changed via the metadata-class in clldutils for reading tables, right? I can't change the encoding from within concepticon.

**Comment by xflr6** [comment]
Ah,  I do not know the exact api there yet. I think it should have an (optional) `encoding=` argument then either way (you might want to load files in other encodings).

**Comment by LinguList** [comment]
So the class I'm talking about is here: https://github.com/clld/clldutils/blob/a66516095f41d000cabb78046fecc11939147f75/clldutils/csvw/metadata.py#L596

This class itself does not allow for defining encoding, I was just trying to figure out, where that happens...

**Comment by LinguList** [comment]
I found the solution. This csvw with metadata is just great: added "utf-8-sig" to my dialect-specification, and all went fine ;-)

```
    "dialect": {
        "header": true,
        "skipBlankRows": true,
        "delimiter": "\t",
	"encoding": "utf-8-sig"
    },
```

**Comment by LinguList** [comment]
I suggest I close this issue here and will just add this to the concepticon directly.

**Comment by xflr6** [comment]
Nice, side note: development on csvw continues here now: https://github.com/cldf/csvw

**Comment by LinguList** [comment]
A side-question: will csvw be included as dependency for clldutils, or may I have to change dependencies in the future for the other projects?

**Comment by xflr6** [comment]
I you use `csvw` directly yes (if you want to keep up with the latest version).
Not sure but I thought  usually one woud `require=pycldf` which depends on `csvw` which (at least currently) depends on `clldutils`.

**Comment by LinguList** [comment]
Well, in the current LingPy-2.6 version, I tried to avoid using pycldf as a dependency at this stage, so reading from cldf is done with clldutils.csvw.

**Comment by LinguList** [comment]
Well: 2.6 is under review, it is not yet released...
