### ISSUE TITLE
Windows does not like git_describe()

### ISSUE THREAD

**Issue by chrzyki** [clld/clldutils#77]
Here:

https://github.com/clld/clldutils/blob/7b8587ef5b56a2fc6cafaff90bc5004355c2b13f/src/clldutils/path.py#L199-L218

Particularly L208.

`FileNotFoundError: [WinError 2] The system cannot find the file specified`. I think that this is a specific combination of issues due to network paths. Note that `lexibank curate` etc. initialises fine (i.e. only `git_describe()` has issues with this path). Will investigate further.

**Comment by chrzyki** [comment]
Doesn't appear to be an issue with network mapped drives, also happens for locally installed versions of Glottolog/Concepticon.

**Comment by xrotwang** [comment]
`git_describe` is not really considered essential functionality, but rather a convenience wrapper. So above all, we want it to not cause exceptions. Would ignoring `FileNotFoundError` in line 214 fix this issue then?
