### ISSUE TITLE
Regex for finding SFM markers too narrow

### ISSUE THREAD

**Issue by johenglisch** [clld/clldutils#91]
Problem: The regex for finding SFM markers only allows numbers at the *end* of a marker:
    https://github.com/clld/clldutils/blob/92ab4cab4f9a39e0d6f20f09ef75e0ea4a11d025/src/clldutils/sfm.py#L21
However, a recent Flex export generated markers of the shape `\z10_Eng`.
Potential fix: A less narrow regex, e.g.:
    MARKER_PATTERN = re.compile('\\\\(?P<marker>[A-Za-z0-9][A-Za-z0-9_]*)(\s+|$)')

**Comment by xrotwang** [comment]
@johenglisch fix is released with clldutils 3.5.1
