### ISSUE TITLE
Subcommand registration fails if no docstring is provided

### ISSUE THREAD

**Issue by chrzyki** [clld/clldutils#92]
Currently, sub-commands can't be registered without them having a docstring due to this conditional:

https://github.com/clld/clldutils/blob/93d3789175103d6f60eb33ef7f4779177ec9993f/src/clldutils/clilib.py#L195

If a docstring is something we want to enforce for sub-commands, this should fail more informatively. If not, change the conditional to `mod.__doc__.strip().splitlines()[0] if mod.__doc__ else ''`?

**Comment by xrotwang** [comment]
We want to enforce docstrings, so better error message is the preferred
solution.

Christoph Rzymski <notifications@github.com> schrieb am Do., 20. Aug. 2020,
12:32:
